pipelines:
  default:
    - parallel:
        - step:
            caches:
              - gradle
            name: Debug Build
            image: runmymind/docker-android-sdk
            script:
              - chmod a+x ./gradlew
              - ./gradlew assembleDebug
            artifacts:
              - app/build/outputs/**

        - step:
            name: Test with Coverage
            image: runmymind/docker-android-sdk
            script:
              - ./gradlew test
              - ./gradlew createDebugCoverageReport

  branches:
    master:
      - parallel:
          - step:
              name: Build Debug
              caches:
                - gradle
              image: runmymind/docker-android-sdk
              script:
                - echo "$SIGNING_JKS_FILE" | base64 -d > upload-keystore.jks
                - ./gradlew assembleDebug
              artifacts:
                - app/build/outputs/**

          - step:
              name: Test
              image: runmymind/docker-android-sdk
              script:
                - ./gradlew test
                - ./gradlew createDebugCoverageReport