name: Android CI

on:
  push:
    branches: [ master, feature/*, feature/astyagov/* ]
  pull_request:
    branches: [ master, feature/* ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug # build
      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: gradle*
          # An explicit key for restoring and saving the cache
          key: messenger-key

  tests:

    needs: [ build ]

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Run all tests with Jacoco coverage
        uses: ReactiveCircus/android-emulator-runner@v2.15.0
        with:
          api-level: 29
          script: ./gradlew totalTestCoverage --stacktrace

      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: |
            ./build/jacocoHtml/
            ./app/build/reports/jacoco/totalTestCoverage/

  jacoco-badge:

    needs: [ tests ]

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Generate JaCoCo Badges
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.1.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: ./app/build/reports/jacoco/totalTestCoverage/totalTestCoverage.csv
          coverage-badge-filename: jacoco.svg
          branches-badge-filename: branches.svg

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'deledzis'
            git config --global user.email 'deledzis@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi