name: Android CI

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master, feature/* ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug # build
      - name: Run Tests
        run: ./gradlew test
      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: gradle*
          # An explicit key for restoring and saving the cache
          key: messenger-key
